---
- hosts: test
  become: yes
  tasks:
  - name: create new user tony
    ansible.builtin.user:
      name: tony
#      state: absent
#      remove: true
      shell: /bin/bash
      password: $6$hz9oxp4u4nSvwX2e$XnE5ubogiEYOeuchODKjxQc3o5ruHW3CAaycjl9R9lfBW0GnzKORgoF0UKYQvu5cXhwC4bHjIu5UqGAG3.1s51
#
#create passwords:: mkpasswd --method=sha-512
