---
- hosts: yum
  tasks:
  - name: Install base packages for RPM based distro's
    yum:
      name: 
      - unzip
      - ssmtp
      - sysstat
      - ntpdate
      - nmap
      - zabbix-agent
      - sudo
      - screen
      - vim-enhanced
      - mailutils
      - git
      - ntp
      - ranger
      - ncal
      - qemu-guest-agent
      state: present
      update_cache: yes
    become: true
    register: yum_update_status
