---
- hosts: all
  become: yes
  tasks:
  - name: Install packages
    apt:
      name:
      - ssmtp
      - sysstat
      - ntpdate
      - nmap
      - zabbix-agent
      - sudo
      - debian-goodies
      - screen
      - vim
      - mailutils
      - git
      - ntp
      - ranger
      - ncal
      - qemu-guest-agent
      state: latest
      cache_valid_time: 3600
