#config-file-copy-multiple.yaml
#10-9-2022 AJM
#to copy multiple configuration files to multiple destinations
#
#
--- 
- hosts: test
  become: yes
  tasks:
      - name: Copy some files 
        copy:
          src: "{{ item.src }}"
          dest: "{{ item.dest }}"
          owner: root
          group: root
          mode: 0644
        with_items:
        - { src: 'files/ssmtp.conf', dest: '/etc/ssmtp/' }
        - { src: 'files/revaliases', dest: '/etc/ssmtp/' }
        - { src: 'files/ntp-client-001.conf', dest: '/etc/ntp.conf' }
        - { src: 'files/rsyslog.conf', dest: '/etc/rsyslog.conf' }

