#copy_file.yaml
#
#Copying file to a non-existing directory perfect for .config files yay!
#
#If the destination directory does not exist, the copy module takes care of creating it and #copying the file to the new directory with the same name as the source file name.
#
# copy_file.yml
---
- name: copy files to destination
  hosts: apt
  tasks:
    - name: copy src.txt to a non existing directory
      copy:
        src: files/00aptproxy
        dest: /etc/apt/apt.conf.d
      tags:
        - dir_not_exist
