---
- hosts: localhost
  connection: local
  become: yes
  tasks:

  - name: Install packages
    apt:
      name:
      - ssmtp
      - sysstat
      - ntpdate
      - nmap
      - zabbix-agent
      - sudo
      - debian-goodies
      - screen
      - vim
      - mailutils
      - git
      - ranger
      state: latest
      cache_valid_time: 3600
