#remove-package.yml
#10-9-2022
#
#Does not actually remove package but disables and stops the service
#
---
- hosts: all
  become: yes
  tasks:
    - name: Remove postfix
      apt:
        name: postfix
        state: absent
