---
- hosts: all
  tasks:
  - name: Update all installed packages using YUM module
    yum:
      name: '*'
      state: latest
      update_cache: yes
      update_only: yes
    register: yum_update_status

  - name: Remove packages that are no longer needed
    yum:
      autoremove: yes

  - name: Reboot when packages are updated
    reboot:
    when: yum_update_status.changed
